#!/usr/bin/python2.7

import sys
import os

from Detection import GetArgs, GetFiles, GetCmd
from Mutation  import RandomMutator, BruteForceMutator, CompleteMutator, InputMutator
from Run       import Runner

def Unbz2(filename):
  dirf = filename.replace(".tar.bz2","")

  #os.system("tar -xf "+ filename)
  #os.system("rm -f -R "+dirf)
  return dirf
  
target = sys.argv[1]
dirf = Unbz2(target)
os.chdir(dirf)
cmd = GetCmd(None) 

os.chdir("crash")
inputs = InputMutator(GetArgs(), GetFiles(), CompleteMutator)

#f = lambda i: i.PrepareData()

#args = GetArgs()
#files = GetFiles()
#mutator = RandomMutator(args[1])

#for i in range(0):
#  mutator.Mutate()

#args[0] = mutator.Mutate()

#r = r + " \"" + " ".join(map(f,args)) + " " + "".join(map(f,files)) + " > /dev/null 2> /dev/null\""
#r = " \"" + inputs.GetMutatedInput() + " > /dev/null 2> /dev/null\""


for i in range(10):
  r = inputs.GetMutatedInput() + " > /dev/null 2> /dev/null"
  #print cmd, r

  Runner(["ocean",cmd,r] , None).Run()

#os.system(r)

#with open('getdata.sh', 'w') as f:
#  f.write(r)
#  os.chmod("getdata.sh",0777)

#name = dirf.replace("-report","")
#os.system("printf "+name+",; ./getdata.sh > /dev/null; cat ocean.csv")

#os.close(f)

#x = open("crash.sh").read()


#patchCrash()


